version: '3.1'

services:
  php:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - 80:80
    volumes:
      - ./prestashop:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php.ini
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./dbdata:/var/lib/mysql
      # - ./prestashop.sql:/docker-entrypoint-initdb.d/prestashop.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: prestapass
    cap_add: 
      - SYS_NICE

  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:8080
