version: '3.1'

services:

  prestashop:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prestashop:/var/www/html/
      - ./logs:/var/log/apache2/

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d # This is for auto importing db from dump
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Biznes
      MYSQL_DATABASE: prestashop
    cap_add:
      - SYS_NICE

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
