version: '3.1'

services:
  prestashop:
    image: prestashop/prestashop:1.7.6.8
    environment:
      PS_INSTALL_AUTO: 0
    depends_on: 
      - db
    ports:
      - 80:80
    volumes:
      - ./prestashop:/var/www/html/
      - ./logs:/var/log

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: prestapass
    cap_add: 
      - SYS_NICE

  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - 8080:8080
