<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuz4hjh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuz4hjh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXuz4hjh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXuz4hjh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXuz4hjh\appProdProjectContainer([
    'container.build_hash' => 'Xuz4hjh',
    'container.build_id' => '5157f473',
    'container.build_time' => 1604852927,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuz4hjh');
